### PR TITLE
New Storage model for Keys and Config

### PR DESCRIPTION
**Pull request by xeroc**
I have worked on this (as promised) and came up with this solution

* https://github.com/bitshares/python-bitshares/tree/feature/storage-models

much nicer encapsulated now and allows to replace with your own storage or key-dealing module.
Parts of the library need to me modified still, but the new unit test `tests/test_storage.py` for different storages works now. The libraries comes with a storage
* in RAM
* in sqlite
and allows to distinguish unencrypted from decrypted use of storages

Todo:
- [x] Refactor Storage module
- [x] Develop unit test
- [ ] Compatibility with rest of the existing library
- [ ] Documentation

### Reference
https://github.com/bitshares/python-bitshares/pull/79

### CODE REVIEW

**Comment by jhtitor** [comment]
Thank you for looking into this.

I'm quite scared to merge this, as we already have a working implementation of replaceable storages, but well, it has to be done :) I'll start a similar feature branch.

**Comment by jhtitor** [comment]
In your new `bitshares/storage/__init__.py`, the actual objects are still global and *are* initialized.

https://github.com/bitshares/python-bitshares/blob/feature/storage-models/bitshares/storage/__init__.py#L17

I've dealt with this like so:

https://github.com/bitshares/python-bitshares/pull/79/commits/ad06e9a2dafeb7118a6b85cc5994bd41a371c0ee#diff-a6b70d1a6fef1f001ac31a8bdb748299R498

In that (now obsolete) changeset, all those objects become part of some "storage" super-object, and THAT is what we replace, to avoid creating/dealing with any of the default storages. That also requires a way to provide your own storage to the wallet on init, (or defer to the default one), like here:

https://github.com/bitshares/python-bitshares/pull/79/commits/ad06e9a2dafeb7118a6b85cc5994bd41a371c0ee#diff-f227e8d12081b2dae0e11cc058692b0eR63

Could you please implement some similar feature? Thanks again for dealing with this whole thing.

**Comment by xeroc** [comment]
> In your new bitshares/storage/__init__.py, the actual objects are still global and are initialized.

https://github.com/bitshares/python-bitshares/blob/feature/storage-models/bitshares/bitshares.py#L139

The storage stuff now only declares classes, nothing is initialized, see [here](https://github.com/xeroc/python-graphenelib/blob/feature/operations-refactoring/graphenestorage/__init__.py)

You can easily provide your own store by implementing the inface like [this](https://github.com/xeroc/python-graphenelib/blob/feature/operations-refactoring/graphenestorage/interfaces.py

I do still distinguish between *Configuration* and *Keys* so that you can store those independently.


When instanciating `BitShares()` you can provide a
 * `config_store` for config storage (ConfigInterface) and/or
 * `key_store` for key storage (KeyInterface).

If you don't do that, the defaults are loaded as defined in [here](https://github.com/bitshares/python-bitshares/blob/feature/storage-models/bitshares/storage.py#L16-L27)

**Comment by xeroc** [comment]
Obivously, some more documentation will be provided ..

**Comment by jhtitor** [comment]
> The storage stuff now only declares classes, nothing is initialized, 
> I do still distinguish between Configuration and Keys so that you can store those independently.

Thank you very much for these updates! Looking very promising now, I'll try merging this and report my results.

**Pull request closed without merging**
