### PR TITLE
Add NBS Chain ID

### PR DESCRIPTION
**Pull request by bangzi1001**

### CODE REVIEW

**Comment by abitmore** [comment]
Feel free to fork the repository as long as the license permits. The code is not welcomed here.

**Comment by dls-cipher** [comment]
Plus - copyright infringement is coming to all your registrars and domains. BitShares as a tech and code is free to be forked, but not the brand of it as well - hence trademark.

**Comment by xeroc** [comment]
To be fair, there never was a discussion on how to tread other chain ids in this library.
I agree that forking may be the easiest route, however, that also comes with more work when pushing improvements upstream.

**Comment by xeroc** [comment]
Just to clarify one more thing here. I am not a fan of non-maintainers of this repo to close issues freely. @abitmore either you become the official maintainer or I do it. You can't have it both ways.

**Comment by abitmore** [comment]
@xeroc thanks for the clarification. I'll take a step back next time.

By the way just FYI I did another change when closing this PR, if you've missed it: https://github.com/bitshares/python-bitshares/commit/6de2440a157caac35d39ea0993f4236d73174ad9. I thought it was a non-brainer action. If you think it was inappropriate please feel free to revert.

**Comment by xeroc** [comment]
@abitmore noticed .. next time, please put commits into `develop`. your's kind of troubled me when doing a new release.

**Comment by abitmore** [comment]
> next time, please put commits into `develop`

I am sorry. That commit was in `develop` branch though. Next time I will create a pull request.

**Pull request closed without merging**
