### PR TITLE
add samet fund and credit deal to operations.py

### PR DESCRIPTION
**Pull request by litepresence**
this pull over rides 317 to include samet ops and deal with some bugs in the first pull; indexing error and errant usage of Optional() during credit deal create

### CODE REVIEW

**Comment by xeroc** [comment]
Good work. Would you mind adding some unittests for them?

Its super easy, really.

1. Go to `tests/test_transactions.py`
2. pick an existing one, replace the function name
3. fill in your own operation with some random (but valid) data
4. add a `True` to `self.doit()` as argument `self.doit(True)` which will print the serialized output in the commandline.
5. run `python3 -m pytest tests/test_transactions.py`. Your unittest will break but you will see a long hex string which is what you copy paste into `self.cm = ""` and remove the `True` again.
6. Confirm unittest works still.
7. Done.

**Comment by abitmore** [comment]
[Some tests](https://github.com/litepresence/python-bitshares/pull/11) are failing due to an issue in [python-graphenelib](https://github.com/xeroc/python-graphenelib), see https://github.com/xeroc/python-graphenelib/pull/188 for a potential fix.

**Comment by pi314x** [comment]
Shouldn't the kwargs in Credit_offer_update for delta_amount be the same ([line 1811](https://github.com/litepresence/python-bitshares/blob/c99c6723e72b5d4e99f4b196979a93130b1ecaf1/bitsharesbase/operations.py#L1811))?
`("delta_amount", Optional(Asset(kwargs["fee"]))),`

**Comment by abitmore** [comment]
> Shouldn't the kwargs in Credit_offer_update for delta_amount be the same ([link to code](https://github.com/litepresence/python-bitshares/blob/c99c6723e72b5d4e99f4b196979a93130b1ecaf1/bitsharesbase/operations.py#L1811))? `("delta_amount", Optional(Asset(kwargs["fee"]))),`

See https://github.com/bitshares/python-bitshares/pull/325/commits/e640dc35ffe86f04aee763cfe2891a7acaf29386 .

**Pull request closed without merging**
