### PR TITLE
Add fee calculator to Bitshares object.

### PR DESCRIPTION
**Pull request by jhtitor**
This should NOT be used instead of `get_required_fees` API call (although it should be possible in the future). The main purpose here is to aid Blind Transfers.

### CODE REVIEW

**Comment by xeroc** [comment]
Why would you not always want to obtain the required fee from the API server? What's the usecase (other than removing one API call)?

**Comment by jhtitor** [comment]
1. `get_required_fees` doesn't work correctly for Transfer_from_blind and Blind_transfer operations in bitshares-core. Instead a local fee calculator is used. And yes `5 * GRAPHENE_PRECISION` is hard-coded, on the wallet side!

2. When doing Transfer_from_blind, you have to include the fee INTO Blind_transfer amount, meaning you have to pre-calculate the fee for the operation, before it is fully constructed. This is not a serious issue, as long you only have to do it once, however...

3. ...there is yet another bug/issue in bitshares-core, which forces you to precalculate this fee TWO times, for one and for two outputs, so we can actually avoid TWO round-trips to server.

Plus: I think it's nice to have such a feature. You cache fee definitions, and then you can re-calculate fees locally, without querying the server.

**Comment by xeroc** [comment]
Since this is *stealth* related, can we have a separated utils file or even a Utils class that can deal with those methods?

**Comment by jhtitor** [comment]
Are you asking if there is any specific reason for this to be part of BitShares class and not in a separate class? No, there's no specific reason for that, I just had no idea where to put it. I'll gladly move it out, *however*, I've also noticed that latest `develop` has Fee class. Should this patch be rewritten to utilize that?

**Pull request closed without merging**
